AUTHORS
dhcp/dhcp/dhcpd_update/ciscosmb.conf

Those commits from xivo.solution adds a new MAC address range for Cisco SMB

New mac range cisco smb

---

plugins/xivo-yealink/v81/entry.py
plugins/xivo-yealink/v81/pkgs/pkgs.db
plugins/xivo-yealink/v81/plugin-info
plugins/xivo-yealink/v81/templates/CP860.tpl
plugins/xivo-yealink/v81/templates/W52P.tpl
plugins/xivo-yealink/v81/templates/base.tpl
plugins/xivo-yealink/v81/templates/common/W52P.tpl

Erreur dans le nom du fichier firmware

Patch 1 : erreur nom firmware de la base W52

---

plugins/xivo-yealink/v81/entry.py
plugins/xivo-yealink/v81/pkgs/pkgs.db
plugins/xivo-yealink/v81/plugin-info
plugins/xivo-yealink/v81/templates/CP860.tpl
plugins/xivo-yealink/v81/templates/W52P.tpl
plugins/xivo-yealink/v81/templates/base.tpl
plugins/xivo-yealink/v81/templates/common/W52P.tpl

Ajout du paramètre filemane pour la base W52 et le handset
Permet d'avoir un fichier avec un nom correct (yealink ne compacte plus ces firmwares sur son site web)

Patch 2 : ajout parametre filename

---

plugins/xivo-yealink/v81/entry.py
plugins/xivo-yealink/v81/pkgs/pkgs.db
plugins/xivo-yealink/v81/plugin-info
plugins/xivo-yealink/v81/templates/CP860.tpl
plugins/xivo-yealink/v81/templates/W52P.tpl
plugins/xivo-yealink/v81/templates/base.tpl
plugins/xivo-yealink/v81/templates/common/W52P.tpl

Erreur dans le paramètre indiquant l'adresse du firmware

Patch 3 : erreur common/W52P.tpl

---

plugins/xivo-cisco-sccp/9.4/plugin-info
plugins/xivo-cisco-sccp/common/common.py

Added support for Cisco phones HTTP provisioning (starting 9.3.x firmwares).

Cisco Phones HTTP provisioning

---

plugins/xivo-patton/6.9/entry.py
plugins/xivo-patton/6.9/plugin-info

add SN4112S

---

plugins/wazo-gigaset/N510/entry.py
plugins/wazo-gigaset/N510/pkgs/pkgs.db
plugins/wazo-gigaset/N510/plugin-info
plugins/wazo-gigaset/common/common.py

Update N510 to 42.250 and modify to "default" the lookup directory profile

Firmware update

---

plugins/xivo-aastra/5.0.0/entry.py
plugins/xivo-aastra/5.0.0/pkgs/pkgs.db
plugins/xivo-aastra/5.0.0/plugin-info
plugins/xivo-aastra/build.py

Note: not in testing. Use the plugin repo built by Zuul to test it!

Add Aastra 68xxi 5.0.0 plugin

---

plugins/xivo-yealink/v83/common.py
plugins/xivo-yealink/v83/entry.py
plugins/xivo-yealink/v83/pkgs/pkgs.db
plugins/xivo-yealink/v83/plugin-info
plugins/xivo-yealink/v83/templates/W80B.tpl
plugins/xivo-yealink/v83/templates/common/W60P_W53P.tpl
plugins/xivo-yealink/v83/templates/common/W80B.tpl
plugins/xivo-yealink/v83/templates/common/dect_model.tpl

yealink-v83: generate and add SIP template to line
yealink-v83: refactor DECT handset firmware definitions
yealink-v83: add CP930W support
yealink-v83: add W80B firmware
yealink-v83: update W53H and W56H firmwares
yealink-v83: add W80B

[WAZO-1324] Yealink W80B - reworked

---

plugins/xivo-yealink/v83/common.py
plugins/xivo-yealink/v83/plugin-info
plugins/xivo-yealink/v83/templates/base.tpl
plugins/xivo-yealink/v84/common.py
plugins/xivo-yealink/v84/plugin-info
plugins/xivo-yealink/v84/templates/base.tpl

Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1317

WAZO-1317: add DND action URLs to Yealink v83 and v84

---

plugins/wazo-htek/2.0.4.4.58/entry.py
plugins/wazo-htek/2.0.4.6.41/entry.py
plugins/wazo-htek/2.0.4.6.41/install.md
plugins/wazo-htek/2.0.4.6.41/pkgs/pkgs.db
plugins/wazo-htek/2.0.4.6.41/plugin-info
plugins/wazo-htek/2.0.4.6.41/templates/UC902.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC903.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC912.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC912G.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC923.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC924.tpl
plugins/wazo-htek/2.0.4.6.41/templates/UC926.tpl
plugins/wazo-htek/2.0.4.6.41/templates/base.tpl
plugins/wazo-htek/2.0.4.6.41/templates/common/model.tpl
plugins/wazo-htek/build.py
plugins/wazo-htek/common/common.py

For Devices : UC926 UC924 UC923 UC921 UC912G UC903 UC902
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1750

Add Firmware 2.0.4.6.41

---

plugins/wazo-gigaset/N510/plugin-info
plugins/wazo-gigaset/N510/templates/base.tpl
plugins/wazo-gigaset/N720/plugin-info
plugins/wazo-gigaset/N720/templates/base.tpl
plugins/wazo-gigaset/common/common.py

Gigaset: fix hex vlan id

---

README.md
dhcp/dhcp/dhcpd_update/snom.conf
plugins/wazo-snom/05.20.0001/entry.py
plugins/wazo-snom/05.20.0001/install.md
plugins/wazo-snom/05.20.0001/limitations.md
plugins/wazo-snom/05.20.0001/pkgs/pkgs.db
plugins/wazo-snom/05.20.0001/plugin-info
plugins/wazo-snom/10.1.46.16/plugin-info
plugins/wazo-snom/10.1.49.11/plugin-info
plugins/wazo-snom/10.1.51.12/plugin-info
plugins/wazo-snom/10.1.54.13/plugin-info
plugins/wazo-snom/build.py
plugins/wazo-snom/common_dect/common.py
plugins/wazo-snom/common_dect/templates/M300.tpl
plugins/wazo-snom/common_dect/templates/M700.tpl
plugins/wazo-snom/common_dect/templates/M900.tpl
plugins/wazo-snom/common_dect/templates/base.tpl
plugins/wazo-snom/common_dect/templates/common/snom-general.xml.tpl
plugins/wazo-snom/common_dect/templates/common/snom-model-firmware.htm.tpl.btpl
plugins/wazo-snom/common_dect/templates/common/snom-model-firmware.xml.tpl.btpl
plugins/wazo-snom/common_dect/templates/common/snom-model.htm.tpl.btpl
plugins/wazo-snom/common_dect/templates/common/snom-model.xml.tpl.btpl
plugins/wazo-snom/common_dect/templates/common/web_lang.xml.tpl
plugins/wazo-snom/common_dect/templates/other/base.htm.tpl

Lots of limitations with this one. See the `limitations.md` file for more info.

WAZO-2208: add Snom MX00 DECT

---

zuul.d/pre-run.yaml
zuul.yaml

Zuul migration

---

plugins/wazo-gigaset/N510/plugin-info
plugins/wazo-gigaset/N510/templates/base.tpl

Hello,
As in #141, let's support N510 firmware update through Wazo Stack.
Thank you 👍

Gigaset N510 support firmware update through Stack

---

plugins/wazo-snom/common/common.py

Hello,
Here's a very quick Snom fix.
I did not bump plugin version intentionally, as we already bump it a few minutes ago.
Thx 👍

Snom quick fix

---

plugins/wazo-fanvil/common/templates/X7C.tpl
plugins/wazo-fanvil/serie-x/pkgs/pkgs.db
plugins/wazo-fanvil/serie-x/plugin-info

Update firmware and key correction (limited to the first 12 keys)

Fanvil x7c key correction and last firmware

---

plugins/wazo-yealink/v85/pkgs/pkgs.db
plugins/wazo-yealink/v85/plugin-info

Yealink v85 links

---

plugins/wazo-fanvil/common/common.py
plugins/wazo-fanvil/common/templates/base-new.tpl
plugins/wazo-fanvil/serie-x/plugin-info

Corrects the non presence of the port in the url and the protocol FTP and not HTTP

Corrects Fanvil PORT and PROTOCOL

---

plugins/xivo-cisco-spa/7.5.5/plugin-info
plugins/xivo-cisco-spa/ata190-1.2.2/plugin-info
plugins/xivo-cisco-spa/common/common.py
plugins/xivo-cisco-spa/legacy/plugin-info
plugins/xivo-cisco-spa/pap2t-5.1.6/plugin-info
plugins/xivo-cisco-spa/spa100-1.3.5p/plugin-info
plugins/xivo-cisco-spa/spa2102-5.2.12/plugin-info
plugins/xivo-cisco-spa/spa3102-5.1.10/plugin-info
plugins/xivo-cisco-spa/spa8000-6.1.11/plugin-info
plugins/xivo-cisco-spa/spa8800-6.1.7/plugin-info

The Cisco downloader does not exist anymore.

[WAZO-2921] cisco-spa: remove package ignore when no cisco downloader

---

plugins/wazo-yealink/v85/plugin-info
plugins/wazo-yealink/v85/templates/W60B.tpl
plugins/wazo-yealink/v85/templates/W70B.tpl
plugins/wazo-yealink/v85/templates/W90B.tpl

dsskey_deal_type normalization

---

plugins/wazo-yealink/v86/common.py
plugins/wazo-yealink/v86/plugin-info

add new expansion keys for new devices

add expansion module

---

plugins/wazo-cisco-sip/common/common.py
plugins/wazo-digium/common/common.py
plugins/wazo-gigaset/N870-83.v2.39.0/common.py
plugins/wazo-gigaset/N870-83.v2.48.0/common.py
plugins/wazo-gigaset/common/common.py
plugins/wazo-grandstream/common/common.py
plugins/wazo-grandstream/common_ata/common.py
plugins/wazo-patton/common/common.py
plugins/wazo-yealink/common/common.py
plugins/wazo-yealink/v82/common.py
plugins/wazo-yealink/v83/common.py
plugins/wazo-yealink/v83/plugin-info
plugins/wazo-yealink/v83/templates/base.tpl
plugins/wazo-yealink/v84/common.py
plugins/wazo-yealink/v85/common.py
plugins/wazo-yealink/v86/common.py
plugins/wazo-yealink/v86/plugin-info
plugins/wazo-yealink/v86/templates/base.tpl

yealink remote controll

---

plugins/wazo-yealink/common/common.py
plugins/wazo-yealink/v82/common.py
plugins/wazo-yealink/v82/plugin-info
plugins/wazo-yealink/v83/common.py
plugins/wazo-yealink/v83/plugin-info
plugins/wazo-yealink/v84/common.py
plugins/wazo-yealink/v84/plugin-info
plugins/wazo-yealink/v85/common.py
plugins/wazo-yealink/v85/plugin-info
plugins/wazo-yealink/v86/common.py
plugins/wazo-yealink/v86/plugin-info

Add Italian support to Yealink

yealink: add Italian language

---

plugins/wazo-cisco-sip/11.1.0/plugin-info
plugins/wazo-cisco-sip/11.1.0/templates/base.tpl
plugins/wazo-cisco-sip/11.1.0/templates/common/model.cfg.tpl

- change option for admin/user password
- add profile rule A for local provisioning

miscellaneous fixes

---

plugins/wazo-gigaset/N510/plugin-info
plugins/wazo-gigaset/N510/templates/base.tpl

Note: has not yet been tested on a phone

Add default value for proxy port to Gigaset N510 avoid it crashing

---

.pre-commit-config.yaml

Depends-on: https://github.com/wazo-platform/wazo-provd-plugins/pull/208

Add more pre commit hooks

---

plugins/Makefile
test-requirements.txt

Makefile: use long syntax options

---

plugins/wazo_fanvil/build.py
plugins/wazo_fanvil/common/common.py
plugins/wazo_fanvil/common/templates/H2U.tpl
plugins/wazo_fanvil/common/templates/base-h-series.tpl
plugins/wazo_fanvil/common/templates/common/model-h2x.tpl
plugins/wazo_fanvil/serie_h/entry.py
plugins/wazo_fanvil/serie_h/install.md
plugins/wazo_fanvil/serie_h/pkgs/pkgs.db
plugins/wazo_fanvil/serie_h/plugin-info

**Add support for Fanvil series H:**
* H2U
**Specific function keys attribution:**
* 1 to 10 => speeddial on memory keys (long press 1 for dial function Key custom 1 for exemple)
* 11 => Only for speeddial emergency button

New support Fanvil H2U

---

plugins/wazo_fanvil/common/templates/common/model-v6x.tpl
plugins/wazo_fanvil/serie_v/plugin-info

* add good version in common file

Fix error firmware version

---

plugins/wazo_fanvil/common/templates/common/model-i10.tpl
plugins/wazo_fanvil/common/templates/common/model-i1x.tpl
plugins/wazo_fanvil/common/templates/common/model-i5x.tpl
plugins/wazo_fanvil/common/templates/common/model-i6x.tpl
plugins/wazo_fanvil/serie_i/plugin-info

Fix common file FW version

---

plugins/wazo_fanvil/common/common.py
plugins/wazo_fanvil/common/templates/base-V67.tpl
plugins/wazo_fanvil/serie_v/plugin-info

* fix BLF support type
* fix V67 template ligne attribution

Fanvil: Fix BLF index

---

plugins/wazo_fanvil/common/templates/base-V-series.tpl
plugins/wazo_fanvil/common/templates/base-V67.tpl
plugins/wazo_fanvil/common/templates/base-h-series.tpl
plugins/wazo_fanvil/common/templates/base-i-series.tpl
plugins/wazo_fanvil/common/templates/base-new.tpl
plugins/wazo_fanvil/serie_h/plugin-info
plugins/wazo_fanvil/serie_i/plugin-info
plugins/wazo_fanvil/serie_v/plugin-info
plugins/wazo_fanvil/serie_x/plugin-info

Improve template for all models because it affected the ability to receive a call as well as make another call.

Fix ring priority

---

plugins/wazo_fanvil/common/common.py
plugins/wazo_fanvil/common/templates/base-V67.tpl
plugins/wazo_fanvil/serie_v/plugin-info

* Fix base template statement
* improve global common file type key type

V67 - Fix error when blf is generated

---

plugins/wazo_fanvil/common/common.py
plugins/wazo_fanvil/common/templates/base-V-series.tpl
plugins/wazo_fanvil/common/templates/base-V67.tpl
plugins/wazo_fanvil/common/templates/base-i-series.tpl
plugins/wazo_fanvil/common/templates/common/model-i5x.tpl
plugins/wazo_fanvil/common/templates/common/model-v67.tpl
plugins/wazo_fanvil/serie_h/plugin-info
plugins/wazo_fanvil/serie_i/entry.py
plugins/wazo_fanvil/serie_i/pkgs/pkgs.db
plugins/wazo_fanvil/serie_i/plugin-info
plugins/wazo_fanvil/serie_v/entry.py
plugins/wazo_fanvil/serie_v/pkgs/pkgs.db
plugins/wazo_fanvil/serie_v/plugin-info
plugins/wazo_fanvil/serie_x/plugin-info
plugins/wazo_fanvil/v2_3/plugin-info

[WAZO-3785] - Fix directory access

---

plugins/wazo_fanvil/common/templates/base-V-series.tpl
plugins/wazo_fanvil/common/templates/common/model-v64.tpl
plugins/wazo_fanvil/common/templates/common/model-v65.tpl
plugins/wazo_fanvil/serie_v/entry.py
plugins/wazo_fanvil/serie_v/pkgs/pkgs.db
plugins/wazo_fanvil/serie_v/plugin-info

Firmware update to fix provisioning issues related to directory access URL.

[WAZO-3876] V64-65 new firmware

---

plugins/wazo_yealink/v85/entry.py
plugins/wazo_yealink/v85/pkgs/pkgs.db
plugins/wazo_yealink/v85/plugin-info

Yealink | W70B | Update Firmware

---

plugins/wazo_yealink/v85/plugin-info
plugins/wazo_yealink/v85/templates/W75B.tpl
plugins/wazo_yealink/v85/templates/W75DM.tpl
plugins/wazo_yealink/v85/templates/W80B.tpl
plugins/wazo_yealink/v85/templates/W80DM.tpl
plugins/wazo_yealink/v85/templates/W90DM.tpl
plugins/wazo_yealink/v85/templates/base.tpl
plugins/wazo_yealink/v86/plugin-info
plugins/wazo_yealink/v86/templates/base.tpl

⚒️ Here we fix a date display issue that was not dynamic in relation to the locale. The variable provided for this purpose was not applied in the templates.
We have also optimized for Dect.
✅ Fixed and tested for plugin v85 and v86

YEALINK | v85 & v86 | Date Variable

---

README.md
plugins/wazo_yealink/v86/common.py
plugins/wazo_yealink/v86/entry.py
plugins/wazo_yealink/v86/pkgs/pkgs.db
plugins/wazo_yealink/v86/plugin-info
plugins/wazo_yealink/v86/templates/AX83H.tpl

🎊 Add new supported device : AX83H

YEALINK | AX83H | Add device

---

dhcp/dhcp/dhcpd_update/snom.conf
plugins/wazo_snom/build.py
plugins/wazo_snom/common_dect/common.py
plugins/wazo_snom/common_dect/templates/M400.tpl
plugins/wazo_snom/common_dect/templates/M900.tpl
plugins/wazo_snom/common_dect/templates/base-new.tpl
plugins/wazo_snom/common_dect/templates/common/snom-model-firmware-740.htm.tpl.btpl
plugins/wazo_snom/common_dect/templates/common/snom-model-firmware-740.xml.tpl.btpl
plugins/wazo_snom/common_dect/templates/common/snom-model-new.htm.tpl.btpl
plugins/wazo_snom/common_dect/templates/common/snom-model-new.xml.tpl.btpl
plugins/wazo_snom/v07_40_0104/entry.py
plugins/wazo_snom/v07_40_0104/install.md
plugins/wazo_snom/v07_40_0104/limitations.md
plugins/wazo_snom/v07_40_0104/pkgs/pkgs.db
plugins/wazo_snom/v07_40_0104/plugin-info

**New plugin for Snom in version 7.40** 
* Add M400
* New firmwares for M900 serie
* New firmwares for Handset (M30, M65, M70, M80, M85 & M90)

SNOM | M400 ability & New Firmwares for M Series

---

plugins/wazo_gigaset/Nx70_83_v2_62_1/common.py
plugins/wazo_gigaset/Nx70_83_v2_62_1/entry.py
plugins/wazo_gigaset/Nx70_83_v2_62_1/install.md
plugins/wazo_gigaset/Nx70_83_v2_62_1/limitations.md
plugins/wazo_gigaset/Nx70_83_v2_62_1/pkgs/pkgs.db
plugins/wazo_gigaset/Nx70_83_v2_62_1/plugin-info
plugins/wazo_gigaset/Nx70_83_v2_62_1/templates/base.tpl
plugins/wazo_gigaset/build.py

Hello,
This PR adds firmware [v2.62.1](https://teamwork.gigaset.com/gigawiki/pages/viewpage.action?pageId=1552679045&src=contextnavpagetreemode) to Gigaset Nx70, copying v2.49.1 tree.
I also enables a [feature](https://teamwork.gigaset.com/gigawiki/pages/viewpage.action?pageId=1346771233) which delays firmware update when there are active calls.
Thank you 👍

Gigaset Nx70 v2_62_1 plugin
