plugins/xivo-aastra/3.3.1-SP4/pkgs/pkgs.db
I fixed all URLs, except for 6753i, but I could not find these URLs because the page is almost empty http://www.mitel.com/open-solutions-documents/6753
=> Fix mitel.com download URLs for Aastra phones

plugins/xivo-snom/10.1.20.0/plugin-info, plugins/xivo-snom/10.1.26.1/plugin-info, plugins/xivo-snom/8.7.5.35/plugin-info, plugins/xivo-snom/8.9.3.40/plugin-info, plugins/xivo-snom/8.9.3.60/plugin-info, plugins/xivo-snom/8.9.3.80/plugin-info, plugins/xivo-snom/common/common.py, plugins/xivo-snom/common/templates/common/snom-model-firmware.xml.tpl.btpl
reason: snom720 does not send MAC in HTTP headers, making the firmware
file request look like an unknown device to provd.
Before: 
```
2019-12-04 13:34:56,735 [1644] (INFO) (twisted): x.x.x.x - - [04/Dec/2019:12:34:56 +0000] "GET /firmware/snom720-8.7.5.35-SIP-r.bin HTTP/1.1" 404 160 "-" "Mozilla/4.0 (compatible; snom720 8.7.5.35)"
```
After:
```
2020-01-14 09:07:53,364 [20037] (INFO) (twisted): x.x.x.x - - [14/Jan/2020:14:07:53 +0000] "GET /firmware/snom720-8.9.3.80-SIP-r.bin?mac=000000000000 HTTP/1.1" 200 22092256 "-" "Mozilla/4.0 (compatible; snom720 8.9.3.80)" 
```
ps: plugin already in testing repo
=> xivo-snom: add MAC in firmware URL

plugins/xivo-aastra/3.3.1-SP4/pkgs/pkgs.db, plugins/xivo-aastra/3.3.1-SP4/plugin-info, plugins/xivo-aastra/4.2.0/pkgs/pkgs.db, plugins/xivo-aastra/4.2.0/plugin-info, plugins/xivo-aastra/4.3.0/pkgs/pkgs.db, plugins/xivo-aastra/4.3.0/plugin-info, plugins/xivo-aastra/5.0.0/pkgs/pkgs.db
Mitel moved everything to subdirectory `/mitel/file/zip/open-solutions/`
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1706
=> WAZO-1706: fix Aastra/Mitel firmware links

plugins/xivo-aastra/3.3.1-SP4/plugin-info, plugins/xivo-aastra/4.2.0/plugin-info, plugins/xivo-aastra/4.3.0/plugin-info, plugins/xivo-aastra/5.0.0/plugin-info, plugins/xivo-aastra/common/common.py
When the SIP port is not defined in the provisioning configuration, it should be 5060, not 0.
This causes issues with phones that cannot make calls if the port is set to 0.
=> WAZO-1713: fix aastra default values

plugins/xivo-cisco-spa/common/templates/base.tpl
This reverts commit bfbc63e6a1c4c33ce1acccc63ac0fe4bbf0ab6a5.
This config is not working, and some time prevent phone to get his config properly.
=> Revert "set dscp 46 for cisco spa phone"

plugins/xivo-yealink/v83/common.py, plugins/xivo-yealink/v83/plugin-info
This bug has been introduced by the addition of W80B previously.
=> [WAZO-1787] Yealink: fix proxy_port missing on line in v83

plugins/wazo-gigaset/N510/entry.py, plugins/wazo-gigaset/N510/pkgs/pkgs.db, plugins/wazo-gigaset/N510/plugin-info, plugins/wazo-gigaset/N510/templates/base.tpl, plugins/wazo-gigaset/common/common.py
Instead of only fixing it, I upgraded to the lastest version.
=> WAZO-2216: fix Gigaset firmware URLs

plugins/xivo-yealink/v85/plugin-info, plugins/xivo-yealink/v85/templates/base.tpl
Why: in a conference, it displays multiple text messages after we are done with
the call. This is not a wanted behaviour in our case.
=> yealink-v85: disable text messaging

plugins/wazo-fanvil/2.3/plugin-info
Why:
* This causes a warning during the generation of the wazo-platform.org
doc
=> fanvil: homogenize metadata for high availability

plugins/xivo-yealink/v85/pkgs/pkgs.db, plugins/xivo-yealink/v85/plugin-info
A bad rebase caused the deletion of this information.
=> Add missing Yealink W90 metadata

plugins/wazo-yealink/v81/entry.py, plugins/wazo-yealink/v81/pkgs/pkgs.db, plugins/wazo-yealink/v81/plugin-info
Based on the previous Yealink PR: https://github.com/wazo-platform/wazo-provd-plugins/pull/100
=> WAZO-2383: fix Yealink v81 firmware links

plugins/wazo-gigaset/N510/plugin-info, plugins/wazo-gigaset/N510/templates/base.tpl
Hello,
This PR enhances Gigaset N510 plugin.
First, it enables firmware auto-update, thanks to properly formatted links provided by Gigaset.
As found in the documentation :
https://teamwork.gigaset.com/gigawiki/display/GPPPO/Direct+link+to+Firmware+file
While here, also update to last firmware version.
https://teamwork.gigaset.com/gigawiki/display/GPPPO/Firmware+N510+IP+PRO
It also properly assign each DECT to its SIP line only.
By default, on N510, all DECT ring / receive calls for all the 6 configured SIP accounts.
And all DECT make outgoing calls from the first configured SIP account.
Which does not make sense...
This PR then properly assign each DECT to its proper SIP account : first DECT to first SIP account, second DECT to second SIP account etc..
Which is then the expected …
=> Gigaset N510 enhancements

plugins/wazo-snom/10.1.101.11/plugin-info, plugins/wazo-snom/common/common.py, plugins/wazo-snom/common/templates/300.tpl, plugins/wazo-snom/common/templates/720.tpl, plugins/wazo-snom/common/templates/725.tpl, plugins/wazo-snom/common/templates/760.tpl, plugins/wazo-snom/common/templates/D735.tpl, plugins/wazo-snom/common/templates/D745.tpl, plugins/wazo-snom/common/templates/D765.tpl, plugins/wazo-snom/common/templates/D785.tpl, plugins/wazo-snom/common/templates/base.tpl, plugins/wazo-snom/common/var/tftpboot/snom-general.xml
Hello,
This PR brings several improvements to the Yealink plugin :
1. It properly adjusts account details display, replacing useless SIP user ID with the extension number.
2. It disable local phonebook if remote phonebook is available (so that we're sure it's properly used).
3. It adjusts `retry_after_failed_register`, making devices to retry faster on their first retries, as some SIP-TLS configured devices systematically wait 2 minutes before registering. Adjusting `retry_after_failed_register` like in this PR solves this issue.
4. It ajusts `provisioning_order`, allowing to provision Snom devices manually. This modification does not break DHCP provisionning, it simply allows devices to provision manually if they do not receive any provisioning option from DHCP.
5. It enables SIP-TLS and …
=> Snom enhancements

plugins/wazo-yealink/v86/plugin-info, plugins/wazo-yealink/v86/templates/base.tpl
Hello,
This PR brings several improvements to the Yealink plugin :
1. It properly adjusts account details display, with its name at the top of the screen, and its number in front of the DSS key.
2. It enlarges DSS key label zones, so that we can display larger labels.
3. It brings a bigger DND logo, so that we easily know DND has been left on.
4. It enables SRTP, if transport is TLS.
Thank you 👍
=> Yealink enhancements

plugins/wazo-gigaset/N720/entry.py, plugins/wazo-gigaset/N720/pkgs/pkgs.db, plugins/wazo-gigaset/N720/plugin-info, plugins/wazo-gigaset/N720/templates/base.tpl
Hi,
This PR brings some enhancements to Gigaset N720 :
1. It enables firmware updates. I found a trick to make the firmware link compliant with what N720 expects (it must end with the binary name), while keeping it served by Wazo itself. Look at the links for technical workaround, self explanatory :) Good news is that I'll be able to replicate this for N510 (see #142) 👍
2. It disables Gigaset.net info/news by default. Privacy is best.
3. It saves some characters on display name, characters are counted on these DECT screens...
4. It updates firmware to last version (tested, no issue with standard features).
5. It properly sets admin password.
Thank you 👍
=> Gigaset N720 enhancements

plugins/wazo-snom/10.1.101.11/pkgs/pkgs.db, plugins/wazo-snom/10.1.101.11/plugin-info
Hello,
This PR solves a bug introduced in #136, during plugin installation :
```
2022-07-04 16:54:29,721 [28336] (ERROR) (provd.app): Error while loading plugin wazo-snom-10.1.101.11
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/provd/app.py", line 824, in _pg_load
self.pg_mgr.load(id, gen_cfg, spec_cfg)
File "/usr/lib/python2.7/dist-packages/provd/plugins.py", line 1134, in load
plugin = obj(self._app, plugin_dir, gen_cfg, spec_cfg)
File "/var/lib/wazo-provd/plugins/wazo-snom-10.1.101.11/common.py", line 153, in __init__
fetchfw_helper = FetchfwPluginHelper(plugin_dir, downloaders)
File "/usr/lib/python2.7/dist-packages/provd/plugins.py", line 554, in __init__
self._pkg_mgr = self._new_pkg_mgr(downloaders, filter_builder)
File …
```
=> Solve bug introduced in #136

plugins/wazo-gigaset/N870-83.v2.48.0/common.py, plugins/wazo-gigaset/N870-83.v2.48.0/entry.py, plugins/wazo-gigaset/N870-83.v2.48.0/install.md, plugins/wazo-gigaset/N870-83.v2.48.0/limitations.md, plugins/wazo-gigaset/N870-83.v2.48.0/pkgs/pkgs.db, plugins/wazo-gigaset/N870-83.v2.48.0/plugin-info, plugins/wazo-gigaset/N870-83.v2.48.0/templates/base.tpl, plugins/wazo-gigaset/build.py
Hello,
This PR brings enhancements for Gigaset N870 devices.
It's a whole copy of `N870-83.v2.39.0` plugin, with following differences :
- fix a bug with `sip_subscribe_mwi` handling preventing provd from building the template
- fix of the `_UA_REGEX` for devices with old firmware (for ex 2.39) which get their new firmware sending their UA between plain double quotes...
- update to last 2.48 firmware version (basic functions tested, working)
- allow mobile devices firmware update
- small cosmetic update on display name, to mimic other Gigaset devices, such as Gigaset N720
- proper SIP TLS / SRTP handling
Unfortunately though, I've encountered a bug between N870 and Asterisk using SIP TLS, where calls are terminated as soon as they're put on hold (which is rather annoying).
I've then …
=> Gigaset N870 enhancements

plugins/wazo-snom/10.1.101.11/plugin-info, plugins/wazo-snom/common/templates/base.tpl, plugins/wazo-yealink/v86/plugin-info, plugins/wazo-yealink/v86/templates/base.tpl
Hello,
When a device is connected to the stack, for the first time, an _autoprov_ configuration template is generated.
There's no problem if this template uses SIP TLS, device will properly reach the stack when provisioning using the  `Provision Extension` method.
However, SRTP can't be used here, because _autoprov_ stack SIP template has it disabled (for good reasons *).
Let's then disable SRTP when in _autoprov_ mode, for both SIP TLS validated plugin ; Snom & Yealink.
Thx 👍
BTW, while here, would really be nice for the _autoprov_ mode to inherit from the _global_ SIP template, so that it would really help for example in NATed environment etc... (see Wazo ticket #5571 / #6066).
(*) Note that even if _autoprov_ mode would inherit from the _global_ SIP template, we would not be able to …
=> Snom, Yealink, allow autoprov with SIP TLS

plugins/wazo-yealink/v86/entry.py, plugins/wazo-yealink/v86/plugin-info
Hi,
Yealink CP920 firmware is declared in `pkgs.db`, but not pushed up to the device.
Let's then fix this.
Thank you 👍
=> Yealink, add CP920 firmware

plugins/wazo-gigaset/Nx70-83.v2.49.1/common.py, plugins/wazo-gigaset/Nx70-83.v2.49.1/entry.py, plugins/wazo-gigaset/Nx70-83.v2.49.1/install.md, plugins/wazo-gigaset/Nx70-83.v2.49.1/limitations.md, plugins/wazo-gigaset/Nx70-83.v2.49.1/pkgs/pkgs.db, plugins/wazo-gigaset/Nx70-83.v2.49.1/plugin-info, plugins/wazo-gigaset/Nx70-83.v2.49.1/templates/base.tpl, plugins/wazo-gigaset/build.py
Hi,
Let's add support for the new Gigaset `N670 IP PRO` (and also for the Gigaset `N870E IP PRO`), which shares exactly the same configuration as the already existing `N870 IP PRO`.
Let's then create a `Nx70 IP PRO` plugin (which is how Gigaset names them).
First commit is then a 1:1 copy of `N870-83.v2.48.0` plugin.
Next commits are modifications, explained below.
It add support for `N670 IP PRO` and  `N870E IP PRO`.
It updates firmware to [last `83.v2.49.1` version](https://teamwork.gigaset.com/gigawiki/pages/viewpage.action?pageId=1350862266).
It enables SIP TLS (kept disabled in #147), which now properly works (`SipProvider.0.UseSIPS` must be set to `0`, after support from Gigaset team).
It properly sets `ToneScheme` according to configured locale.
It deregisters accounts for detached …
=> Gigaset, add support for N670 IP PRO

dhcp/dhcp/dhcpd_update/linksys.conf
New Cisco SPA8000 can come with MAC address prefix 70:1f:53
Consider adding this block inside linksys.conf dhcp_update file
subclass "voip-mac-address-prefix" 70:1f:53:a0 {
if not exists vendor-class-identifier {
option tftp-server-name = config-option VOIP.tftp-server-name;
log(concat("[", binary-to-ascii(16, 8, ":", hardware), "] ", "BOOT Linksys PREFIX 70:1f:53:a0"));
}
}
=> fix : Add new MAC Prefix 70:1f:53 (SPA8000)

plugins/wazo-snom/10.1.141.13/entry.py, plugins/wazo-snom/10.1.141.13/pkgs/pkgs.db, plugins/wazo-snom/10.1.141.13/plugin-info, plugins/wazo-snom/build.py
Hello,
This plugin updates Snom firmware to 10.1.141.13.
https://service.snom.com/display/wiki/10.1.141.13+Release
While here, it also adds new devices to the list : [D713](https://service.snom.com/display/wiki/D713), [D862](https://service.snom.com/display/wiki/D862) and [D865](https://service.snom.com/display/wiki/D865).
Thx 👍
=> Snom, update firmware to 10.1.141.13

plugins/wazo-gigaset/N510/plugin-info, plugins/wazo-gigaset/N510/templates/base.tpl
uiSendMask and uiReceiveMask are bitmasks so power of 2 must be used to do 1:1 assignment properly
=> Proper one-to-one assignement on Gigaset N510 (v2)

plugins/wazo_digium/common/common.py, plugins/wazo_digium/v1_4_0_0/plugin-info, plugins/wazo_digium/v2_2_1_8/plugin-info, plugins/wazo_digium/v2_8_1/plugin-info, plugins/wazo_yealink/v83/plugin-info, plugins/wazo_yealink/v83/templates/base.tpl, plugins/wazo_yealink/v86/plugin-info, plugins/wazo_yealink/v86/templates/base.tpl
why: we want to remove usage of raw_config['ip'] key in order to
deprecate this key. Moreover, a device without line doesn't make sense.
note: autoprov have one sip_line
why:
- we want to remove usage of raw_config['ip'] key in order to deprecate
this key.
- IP is the provisioning server, and action_uri_limit_ip need to have
the PBX server.
note: taking the last line proxy_ip is only for convenience and have the
same issue than taking the first one
=> Pull request for WAZO-3532-use-main-proxy-ip

plugins/wazo_fanvil/common/templates/base-V-series.tpl, plugins/wazo_fanvil/common/templates/base-V67.tpl, plugins/wazo_fanvil/serie_v/entry.py, plugins/wazo_fanvil/serie_v/plugin-info
* fix templates for V6x
* fix number key by page (removing an entry for the page switch)
Tested on V65 (v2.12.16.4) and V67 (v2.6.6.201)
=> Fix function keys page attribution

plugins/wazo_aastra/v6_4_0_SP2/pkgs/pkgs.db, plugins/wazo_aastra/v6_4_0_SP2/plugin-info
It is still possible to load language pack files, so it probably is useful to keep the language pack file even if it's for 5.0 and not 6.4
=> Revert Mitel 6.4.0 language-pack removal

plugins/wazo_gigaset/N720/plugin-info, plugins/wazo_gigaset/N720/templates/base.tpl, plugins/wazo_gigaset/common/common.py
Hello,
Here's a quick fix for Gigaset N720 to tune code tone.
While here, let's remove the `BS_IP_Data.aucS_DATA_SERVER` parameter, which is not a N720 parameter but a N510 one.
Provisioning documentation : https://teamwork.gigaset.com/gigawiki/display/GPPPO/Provisioning+step+by+step
Thank you 👍
=> Gigaset N720, tune code tone

plugins/wazo_polycom/common/templates/base.tpl, plugins/wazo_polycom/v5_4_3/var/tftpboot/common.cfg, plugins/wazo_polycom/v5_9_2/plugin-info
Why: needed when doing requests through NAT
=> polycom: add MAC address to User Agent
